#!/usr/bin/expect -f

set timeout -1

spawn sh tdsetup.ksh

expect "is to be installed"

send -- "/root/TDAccess3.4.0\r"

expect "Create?  <Y>"

send -- "Y\r"

expect "administrative EMail address"

send -- "test@test.com\r"

expect "Install TDServer ?   <Y or N>\r"

send -- "N\r"

expect eof